// generated by stringer -type=State; DO NOT EDIT

package riak_node_states

import "fmt"

const _State_name = "UnknownStartingStartedShuttingDownShutdown"

var _State_index = [...]uint8{0, 7, 15, 22, 34, 42}

func (i State) String() string {
	if i < 0 || i+1 >= State(len(_State_index)) {
		return fmt.Sprintf("State(%d)", i)
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
