// Code generated by protoc-gen-go.
// source: cluster.proto
// DO NOT EDIT!

/*
Package common is a generated protocol buffer package.

It is generated from these files:
	cluster.proto

It has these top-level messages:
	Cluster
*/
package common

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Cluster struct {
	Uuid             *string `protobuf:"bytes,1,req,name=uuid" json:"uuid,omitempty"`
	Nicename         *string `protobuf:"bytes,2,req,name=nicename" json:"nicename,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Cluster) Reset()         { *m = Cluster{} }
func (m *Cluster) String() string { return proto.CompactTextString(m) }
func (*Cluster) ProtoMessage()    {}

func (m *Cluster) GetUuid() string {
	if m != nil && m.Uuid != nil {
		return *m.Uuid
	}
	return ""
}

func (m *Cluster) GetNicename() string {
	if m != nil && m.Nicename != nil {
		return *m.Nicename
	}
	return ""
}

func init() {
}
