.PHONY: all

all: riak_explorer_darwin_amd64.tar.gz riak_explorer_linux_amd64.tar.gz

riak_explorer_darwin_amd64.tar.gz:
	curl -O http://riak-tools.s3.amazonaws.com/riak_explorer_darwin_amd64.tar.gz

riak_explorer_linux_amd64.tar.gz:
	curl -O http://riak-tools.s3.amazonaws.com/riak_explorer_linux_amd64.tar.gz
